language: ruby
rvm:
  - 2.3.1
  - 2.2.5
before_script:
  - bundle exec rake db:migrate RAILS_ENV=test
addons:
  code_climate:
    repo_token: 61c3ea804322306871a6b7e06a0a6435672cd29aea0c2b286e6b837234ba9d90
deploy:
  provider: rubygems
  api_key:
    secure: WxGCqYToLKgYediVNmHUQ5SkJ3hfKIIu6K8b8Fvd4nb2v6p9tUo+Cz4xN/mTU1tUT5xF4D+P3Oek9Ih5GCL56s+i5C8T60v71azupcQoJpr9AlUxNVipJy+BaaNWb/yH2c3GWYtVJmG44s/nBSgG2WJLhkHSjHM+0CuUF0PknW8WUY7+zkZW3XsVh3bv9+O32uSYizdNt2IiccvqcjEKtmD+mZ5U5/Zwosy1ExmGXFXgFCKhK1oBu/ejqQdwRzY3LwquaTg9tEqR3Cl2dwDboXN1Ga5V7Q3+zhqCYPho33CtNr9ZhaeWS/fI3VcUa7O3fzS71JWSn97gqfqhkehXuGbptebLmLOgRjfe7RloH2VVc8NoqTFLYyvptD3522TG/kSH+etOVQgBpTGXf6TDD6FybH/ZQ0efFRzm00feAEmrbW+AkdSonTCVr/LYePnYWBPuBOZmOf2wuV0+84E5Jlw1wFRLG2JzRDWzScREIbZ8Q4ZvUihEKHIy8a76N6TBTRnAQv/FMfpx4wDXWibP3ji7De9HADjgkUOtk5qTKn8flvNGtJ+phBHyNEg0dFVVQdvyxUuhHWZV1SqKZOy4ITRSGzruufnvTrg09HKDDx/jImSrK3mT/64NVLmmnXMCz/CkLXLMcl6cohgyQCugucsNocy66AZYh8fTB3t0LQ4=
  gem: knock
  on:
    tags: true
    repo: nsarno/knock
notifications:
  slack:
    secure: Z/aucu3B6NfMxVOky4FK43hlhrArG7JbkCj6MZvldRzPP5Q/z2GD+isFvvvJVIO92Tu9NkBlGaSYmTKeQH8L5j2oqGKapVfK7zCUuLYuerP96P4OsLywHfH1E9T7xr9lRr/e/oEFmojN4WUoCXCtOUNVLr3e5vGJxmHIwyDKuLZDaTdKmeO6dVBwonkuccgM11d1CQmI9s5IGtv3jtQZGsccVEPQGbCDoD4s4xI8aEcf4YsXdSJ5v8vg0R3XEvc+GTRPvKAdPlKkFHfWgVyu1An0g0hIfX7cvcUEOHiCbstefhAi8AkI9muDqfa2GStOAp5lSdyRs2/MJCr2K7jVNgXfzAg+RarKMpbM9gNAMxL4Qa4O6lwrng5ynL9TUX28uvA4ceLNTycjX/WQdR1EiQf6zS6N/DqxFrCzTE/2JEY4fnaKTt9bmpYMvF+yGDE5TnmrwtUehqCuN8ViSAOFspr6KP947Fu5Q0gDaZAvhiOoDuSYxe1D04f6N+hdaVtrFvPVHWAXp1rR6oQbVAFxJAoh9sAHpI1Fa/y/x1hWJkRf6DFeyRadJblGQsN6894UFlCL6x5RPvT70sZ8EOx6F1EMJpQIKqN7z2bmMkQmsA1RvQm5ZzGqxiwA8ZyyKpUtVYM31hcH1qwGKIUcGkgp0Sv+BHCjW8prnDEK5SARfgI=
